openapi: 3.0.2
info:
  title: Associates API
  version: 1.0.0
  description: API documentation for Associates
servers:
  - url: /api
paths:
  /associates/:
    get:
      tags:
        - associates
      summary: List all associates
      operationId: listAssociates
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of associates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Associate'
        '401':
          description: Unauthorized
    post:
      tags:
        - associates
      summary: Create a new associate
      operationId: createAssociate
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssociateCreate'
      responses:
        '201':
          description: Associate created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Associate'
        '401':
          description: Unauthorized
  /associates/{id}/:
    get:
      tags:
        - associates
      summary: Retrieve an associate
      operationId: getAssociate
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the associate
      responses:
        '200':
          description: Associate retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Associate'
        '404':
          description: Associate not found
        '401':
          description: Unauthorized
    put:
      tags:
        - associates
      summary: Update an associate
      operationId: updateAssociate
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the associate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssociateCreate'
      responses:
        '200':
          description: Associate updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Associate'
        '404':
          description: Associate not found
        '401':
          description: Unauthorized
    delete:
      tags:
        - associates
      summary: Delete an associate
      operationId: deleteAssociate
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the associate
      responses:
        '204':
          description: Associate deleted successfully
        '404':
          description: Associate not found
        '401':
          description: Unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Associate:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        date_of_birth:
          type: string
          format: date
        care_home:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        created_by:
          type: string
    AssociateCreate:
      type: object
      properties:
        name:
          type: string
        date_of_birth:
          type: string
          format: date
        care_home:
          type: string
        created_by:
          type: string
