openapi: 3.0.2
info:
  title: Reports API
  version: 1.0.0
  description: API documentation for Reports
servers:
  - url: /api
paths:
  /reports/:
    get:
      tags:
        - reports
      summary: List all reports
      operationId: listReports
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of reports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
        '401':
          description: Unauthorized
    post:
      tags:
        - reports
      summary: Create a new report
      operationId: createReport
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ReportCreate'
      responses:
        '201':
          description: Report created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        '401':
          description: Unauthorized
  /reports/{id}/:
    get:
      tags:
        - reports
      summary: Retrieve a report
      operationId: getReport
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the report
      responses:
        '200':
          description: Report retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        '404':
          description: Report not found
        '401':
          description: Unauthorized
    put:
      tags:
        - reports
      summary: Update a report
      operationId: updateReport
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the report
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ReportCreate'
      responses:
        '200':
          description: Report updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        '404':
          description: Report not found
        '401':
          description: Unauthorized
    delete:
      tags:
        - reports
      summary: Delete a report
      operationId: deleteReport
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the report
      responses:
        '204':
          description: Report deleted successfully
        '404':
          description: Report not found
        '401':
          description: Unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Report:
      type: object
      properties:
        id:
          type: string
          format: uuid
        report_month:
          type: string
          format: date
        associate:
          type: string
        description:
          type: string
        pdf:
          type: string
          format: binary
    ReportCreate:
      type: object
      properties:
        report_month:
          type: string
          format: date
        associate:
          type: string
        description:
          type: string
        pdf:
          type: string
          format: binary
